# Generated by Django 2.2.18 on 2021-02-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='photo',
            field=models.ImageField(blank=True, default='noimage.png', null=True, upload_to='', verbose_name='Image'),
        ),
    ]
