# Generated by Django 2.2.18 on 2021-02-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_room_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='room',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
